### ISSUE TITLE
Design the Database Schema

### ISSUE THREAD

**Issue by mehalyna** [Project-Stage-Academy/UA_1155_alpha#1]
**Objective**: To create a well-structured database schema that efficiently supports the application's data requirements.

**Sub-Tasks**:
1. **Identify Entities and Relationships**:
   - Analyze the project requirements to identify key entities such as startups, investors, profiles, projects, messages, etc.
   - Determine the relationships between these entities (one-to-many, many-to-many, etc.).

2. **Define Entity Attributes**:
   - List down the attributes for each entity, like startup name, investor details, project descriptions, contact information, etc.

3. **Create ER Diagrams**:
   - Use a database modeling tool to create Entity-Relationship (ER) diagrams representing the structure of the database.

4. **Normalize Database**:
   - Ensure the database design adheres to normalization rules to reduce redundancy and improve data integrity.

5. **Review and Iterate**:
   - Review the schema with the team and iterate based on feedback.

**Comment by Thoughtseize1** [comment]
https://dbdesigner.page.link/XhATdEVdfwaS9ERk7

**Comment by Thoughtseize1** [comment]
![Image](https://github.com/Project-Stage-Academy/UA_1155_alpha/assets/112819029/b249df76-6117-45f5-94fa-f07e3472e88e)
