### ISSUE TITLE
Implementing Viewing Functionality for Projects Profiles

### ISSUE THREAD

**Issue by mehalyna** [Project-Stage-Academy/UA_1155_alpha#13]
1. **Requirement Analysis for Profile Viewing**:
   - Analyze the specific requirements and preferences of investors regarding projects profile viewing.

2. **Enhance Database and API for Profile Information**:
   - Ensure the database contains all relevant information for projects profiles.
   - Develop or update API endpoints to retrieve projects profile information.

3. **Develop Search and Filter Capabilities**:
   - Implement search functionality to allow investors to search for projects by various parameters.
   - Add filtering options based on criteria like industry, investment needs, or company size.

4. **Design User Interface for Profile Browsing** (Optional):
   - Design and implement a user interface that allows investors to browse through projects profiles easily.
   - Ensure the interface is intuitive and provides a smooth browsing experience.

5. **Profile Detail View Implementation**:
   - Develop a detailed view for each startup profile that investors can access to see more information.

6. **Testing Profile Viewing Functionality**:
   - Test the profile viewing feature for functionality, usability, and security.

US #12

**Comment by Thoughtseize1** [comment]
**I should implement GET, SEARCH AND FILTRATIONS of PROJECTS !**
In investor's role!

**Comment by Thoughtseize1** [comment]
Implemented permission checks for each method in ProjectViewSet.

**Created two custom methods:**
- invest_to_project: Allows investors to participate in projects. URL: `/api/projects/3/invest/`
The method currently checks access permissions and verifies whether the user has already invested in the project.
- get_my_projects: Enables investors to view their own projects. URL: `/api/projects/my`

**Implemented project viewing capabilities:**
`/api/projects`: Users can view limited information about all projects.
`/api/projects/12`: Users can view a specific project by ID.

- Investor users can see full project information (including budget and contact details) thanks to the serializer.
- Investor users can view projects they are involved in (by investing through the invest_to_project method).
- Implemented filtering by query parameters:
`/api/projects?project_name=la_&bgt=5000`
`/api/projects?project_name=la_&bgt=5000&blt=9000`
- Filtering is implemented based on query parameters. Investor users can filter projects based on the budget_needed field, while non-investor users cannot use budget filtering.
- Implemented filtering projects by a part of the project name:
`/api/projects?project_name=la_`
- The following fields are allowed for filtering: `'project_name', 'description', 'industry', 'status', 'bgt', and 'blt'`.
```
bgt - budget greater or than 
blt - budget less or equal than 
```
