### ISSUE TITLE
Implement Notification Trigger Mechanism [86-2 Notification Trigger Mechanisms & Services]

### ISSUE THREAD

**Issue by VovaD199** [Project-Stage-Academy/UA_1155_alpha#88]
**Description:**
Develop backend mechanisms that trigger notifications based on specific actions by an investor, such as following a startup's profile or sending a message.

**Acceptance Criteria:**
- Implement event listeners or hooks within the application that detect when an investor follows a profile or sends a message.
- Upon detecting such events, a notification record should be created in the database.
- Ensure that the notification mechanism is efficient and does not introduce significant latency to the investor's actions.

Task #86

**Comment by AlexanderSychev2005** [comment]
The task was completely done in Task #21.
