### ISSUE TITLE
API Endpoints for Managing Email Notification Preferences [86-6]

### ISSUE THREAD

**Issue by VovaD199** [Project-Stage-Academy/UA_1155_alpha#91]
**Description:**
Develop RESTful API endpoints that manage email notification preferences, allowing startups to opt-in or opt-out of receiving notifications for specific types of events via email.

**Acceptance Criteria:**
- Provide API endpoints for startups to customize which notifications they receive via email.
- Ensure users can select events such as new follows, messages, etc., for which they wish to receive email notifications.
- Integrate these settings with the backend logic that handles sending out emails to ensure compliance with user preferences.
- Implement proper authentication and validation to secure access to notification settings.
- Thoroughly document the endpoints, including details on how to use them, expected parameters, and sample responses.

Task #86

**Comment by AlexanderSychev2005** [comment]
The task was completely done in Task #21.
